package jarcassonne.viewController;

import jarcassonne.model.Model;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class EndGame extends javax.swing.JFrame {

    public EndGame() {
    	super("! Game Over !");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Winner = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        player4 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false); // GENIO !!!
        
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel1.setLayout(null);

        Winner.setFont(new java.awt.Font("Ravie", 0, 15)); // NOI18N
        Winner.setForeground(new java.awt.Color(102, 0, 0));
        Winner.setText(ViewControllerForModel.getInstance().winnerOrDraw());
        jPanel1.add(Winner);
        Winner.setBounds(7, -30, 250, 100);

        player1.setForeground(new java.awt.Color(0, 0, 255));
        player1.setSize(0, 21);
        player1.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        player1.setText(Model.getInstance().getNamePlayer1()+" : "+ Model.getInstance().getScore(Model.P1));
        jPanel1.add(player1);
        player1.setBounds(60, 240, 300, 40);

        player2.setForeground(new java.awt.Color(255, 0, 0));
        player2.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        player2.setText(Model.getInstance().getNamePlayer2()+" : "+ Model.getInstance().getScore(Model.P2));
        jPanel1.add(player2);
        player2.setBounds(60, 280, 300, 40);

        player3.setForeground(new java.awt.Color(102, 153, 0));
        player3.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        player3.setText(Model.getInstance().getNamePlayer3()+" : "+ Model.getInstance().getScore(Model.P3));
        jPanel1.add(player3);
        player3.setBounds(60, 320, 300, 40);

        player4.setForeground(new java.awt.Color(255, 153, 0));
        player4.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        player4.setText(Model.getInstance().getNamePlayer4()+" : "+ Model.getInstance().getScore(Model.P4));
        jPanel1.add(player4);
        player4.setBounds(60, 360, 300, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/end.jpg")));
        jPanel1.add(Background);
        Background.setBounds(0, 0, 250, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        if (Model.getInstance().getNumPlayer()==3)
        	player4.setVisible(false);
        if (Model.getInstance().getNumPlayer()==2){
        	player3.setVisible(false);
        	player4.setVisible(false);
        }
        
        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Winner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player3;
    private javax.swing.JLabel player4;
    // End of variables declaration                   
}