package jarcassonne.viewController;

import jarcassonne.model.Model;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.ImageIcon;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


	/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */

	public class NewGameWindow extends javax.swing.JFrame {

	    public NewGameWindow() {
	    	super("! Set Players' Number !");
	        
	       
	        this.background = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/cavalieri.jpg"));
	        
	        initComponents();
	        setLocationRelativeTo(null);	      
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	    	buttonGroup1 = new javax.swing.ButtonGroup();
	        jPanel1 = new javax.swing.JPanel();
	        jTextField1 = new javax.swing.JTextField();
	        jTextField2 = new javax.swing.JTextField();
	        jTextField3 = new javax.swing.JTextField();
	        jTextField4 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jRadioButton1 = new javax.swing.JRadioButton();
	        jRadioButton2 = new javax.swing.JRadioButton();
	        jRadioButton3 = new javax.swing.JRadioButton();
	        jLabel1 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
	        addWindowListener(new WindowAdapter() {
	            public void windowClosing(WindowEvent ev) {
	               ViewControllerForModel.getInstance().closeNewGameWindow();
	               ViewControllerForModel.getInstance().openStartWindow();      	
	                 }            
	          });
	        setPreferredSize(new java.awt.Dimension(500, 469));
	        setResizable(false);

	        jPanel1.setLayout(null);

	        jTextField1.setForeground(new java.awt.Color(0, 0, 255));
	        jTextField1.setDocument(new LengthRestrictedDocument(11)) ;
	        jTextField1.setText("Player 1");
	        jPanel1.add(jTextField1);
	        jTextField1.setBounds(175, 85, 150, 40);
	        jTextField1.setVisible(false);
	        
	        jTextField1.addMouseListener(new MouseAdapter(){
	            public void mouseClicked(MouseEvent e){
	                if(jTextField1.getText().equals("Player 1")){
	                	jTextField1.setText("");
	                    repaint();
	                    revalidate();
	                }           
	            }
	        });

	        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
	        jTextField2.setDocument(new LengthRestrictedDocument(11));
	        jTextField2.setText("Player 2");
	        jPanel1.add(jTextField2);
	        jTextField2.setBounds(175, 145, 150, 40);
	        jTextField2.setVisible(false);
	        
	        jTextField2.addMouseListener(new MouseAdapter(){
	            public void mouseClicked(MouseEvent e){
	                if(jTextField2.getText().equals("Player 2")){
	                	jTextField2.setText("");
	                    repaint();
	                    revalidate();
	                }           
	            }
	        });
	        

	        jTextField3.setForeground(new java.awt.Color(102, 153, 0));
	        jTextField3.setDocument(new LengthRestrictedDocument(11));
	        jTextField3.setText("Player 3");
	        jPanel1.add(jTextField3);
	        jTextField3.setBounds(175, 205, 150, 40);
	        jTextField3.setVisible(false);
	        
	        jTextField3.addMouseListener(new MouseAdapter(){
	            public void mouseClicked(MouseEvent e){
	                if(jTextField3.getText().equals("Player 3")){
	                	jTextField3.setText("");
	                    repaint();
	                    revalidate();
	                }           
	            }
	        });
	       

	        jTextField4.setForeground(new java.awt.Color(255, 153, 0));
	        jTextField4.setDocument(new LengthRestrictedDocument(11));
	        jTextField4.setText("Player 4");
	        jPanel1.add(jTextField4);
	        jTextField4.setBounds(175, 265, 150, 40);
	        jTextField4.setVisible(false);
	        
	        jTextField4.addMouseListener(new MouseAdapter(){
	            public void mouseClicked(MouseEvent e){
	                if(jTextField4.getText().equals("Player 4")){
	                	jTextField4.setText("");
	                    repaint();
	                    revalidate();
	                }           
	            }
	        });

	        jButton1.setText("PLAY");
	        jPanel1.add(jButton1);
	        jButton1.setBounds(360, 370, 100, 40);
	        jButton1.setVisible(false);
        
	        jLabel1.setIcon(background); // NOI18N
	        jPanel1.add(jLabel1);
	        jLabel1.setBounds(0, 0, 500, 469);
	        
	        buttonGroup1.add(jRadioButton1);
	        jRadioButton1.setText("2 Players");
	        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton1ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jRadioButton1);
	        jRadioButton1.setBounds(20, 20, 120, 23);

	        buttonGroup1.add(jRadioButton2);
	        jRadioButton2.setText("3 Players");
	        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton2ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jRadioButton2);
	        jRadioButton2.setBounds(210, 20, 120, 23);

	        buttonGroup1.add(jRadioButton3);
	        jRadioButton3.setText("4 Players");
	        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton3ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jRadioButton3);
	        jRadioButton3.setBounds(400, 20, 120, 23);

	        jLabel1.setIcon(this.background); // NOI18N
	        jPanel1.add(jLabel1);
	        jLabel1.setBounds(0, 0, 500, 469);

	        
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        
	        if (Model.getInstance().getNumPlayer()==3)
	        	jTextField4.setVisible(false);
	        if (Model.getInstance().getNumPlayer()==2){
	        	jTextField3.setVisible(false);
	        	jTextField4.setVisible(false);
	        }
	        
	        pack();
	    }// </editor-fold>                       
	    
	    
	    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        jTextField1.setVisible(true);
	        jTextField2.setVisible(true);
	        jTextField3.setVisible(false);
	        jTextField4.setVisible(false);
	        jTextField1.setBounds(175, 145, 150, 40);
	        jTextField2.setBounds(175, 205, 150, 40);
	        Model.getInstance().setNumPlayer(2);
	        jButton1.setVisible(true);
	     }                                             

	    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	    	jTextField1.setVisible(true);
	        jTextField2.setVisible(true);
	        jTextField3.setVisible(true);
	        jTextField4.setVisible(false);
	        jTextField1.setBounds(175, 85, 150, 40);
	        jTextField2.setBounds(175, 175, 150, 40);
	        jTextField3.setBounds(175, 265, 150, 40);
	        Model.getInstance().setNumPlayer(3);
	        jButton1.setVisible(true);
	     }                                             

	    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        jTextField1.setVisible(true);
	        jTextField2.setVisible(true);
	        jTextField3.setVisible(true);
	        jTextField4.setVisible(true);
	        jTextField1.setBounds(175, 85, 150, 40);
	        jTextField2.setBounds(175, 145, 150, 40);
	        jTextField3.setBounds(175, 205, 150, 40);
	        jTextField4.setBounds(175, 265, 150, 40);
	        Model.getInstance().setNumPlayer(4);
	        jButton1.setVisible(true);
	     }                                             	    

	    protected void jButton1ActionPerformed(ActionEvent evt) {
			ViewControllerForModel.getInstance().closeNewGameWindow();
			ViewControllerForModel.getInstance().openMainGUI();
			
			 Model.getInstance().setNamePlayer1(jTextField1.getText());
			 Model.getInstance().setNamePlayer2(jTextField2.getText());
			 Model.getInstance().setNamePlayer3(jTextField3.getText());
			 Model.getInstance().setNamePlayer4(jTextField4.getText());
		}

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(NewGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(NewGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(NewGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(NewGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new NewGameWindow().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JRadioButton jRadioButton1;
	    private javax.swing.JRadioButton jRadioButton2;
	    private javax.swing.JRadioButton jRadioButton3;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    
	    
	    private ImageIcon background;
	    // End of variables declaration                   
	
	
	public class LengthRestrictedDocument extends PlainDocument {

		private StringBuffer cache = new StringBuffer();
		int lunghezzaMax;

		public LengthRestrictedDocument(int lunghezzaMax){
		this.lunghezzaMax = lunghezzaMax-1;	
		}

		public void insertString(int off, String s, AttributeSet aset) throws BadLocationException{
		int len = getLength();	
		if(len >= this.lunghezzaMax) { 
		return; 
		} //MAX CARATTERI

		cache.setLength(0);	
		char c;	
		for(int i = 0; i < s.length(); i++) {
			c = s.charAt(i);	
			cache.append(c);
			if(cache.length() >= lunghezzaMax - len) { 
				break; 
				}	
			}	
		if(cache.length() > 0){
			super.insertString(	off, cache.toString(), aset);
			}	
		}
		}
	}	
