package jarcassonne.viewController;

import jarcassonne.model.Model;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import javax.swing.ImageIcon;

public class StartWindow extends javax.swing.JFrame {

    public StartWindow() {
    	super("! Welcome in Jarcassonne !");   
        
         this.background = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/sfondo.jpg"));
         this.np = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/np.png"));
         this.cp = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/cp.png"));
         this.stat = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tut.png"));
         this.reg = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/regol.png"));

        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 630));
        jPanel1.setLayout(null);

        jButton1.setIcon(this.np); // NOI18N
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 90, 220, 70);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton4ActionPerformed(evt);
				} catch (URISyntaxException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
 
        jButton2.setIcon(cp); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 170, 220, 70);

        jButton3.setIcon(stat); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 430, 220, 70);

        jButton4.setIcon(reg); // NOI18N
        jButton4.setContentAreaFilled(false);
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 510, 220, 70);

        jLabel1.setIcon(background); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        ViewControllerForModel.getInstance().closeStartWindow();
        ViewControllerForModel.getInstance().openNewGameWindow();
        
    } 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {   
    	String file = ViewControllerForModel.getInstance().openFile();
    	if (file!= null){
    		try{
    			Model.getInstance().loadModelFromFile(file);
    			ViewControllerForModel.getInstance().closeStartWindow();
    			ViewControllerForModel.getInstance().openMainGUI();
    			
    		}catch (java.io.FileNotFoundException e1){
    			ViewControllerForModel.getInstance().showCannotFindFileMessage(file);
    		}catch (java.io.IOException e2) {
    			ViewControllerForModel.getInstance().showCannotFindFileMessage(file);
			}    		  		
    	}      
    } 
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        ViewControllerForModel.getInstance().closeStartWindow();
        ViewControllerForModel.getInstance().openTutorial();
    } 
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws URISyntaxException,IOException {                                               
        Desktop.getDesktop().browse(new URI("http://www.regoledelgioco.com/giochi-da-tavolo-di-ruolo-strategia/carcassone/"));
    } 
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	ViewControllerForModel.getInstance().openStartWindow();
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    
    private ImageIcon background;
    private ImageIcon np;
    private ImageIcon cp;
    private ImageIcon stat;
    private ImageIcon reg;
    // End of variables declaration          
}
