package jarcassonne.viewController;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.event.MouseInputListener;

public class TutorialWindow extends javax.swing.JFrame implements MouseInputListener{
	int k;
    /**
     * Creates new form TutorialWindow
     */
    public TutorialWindow() {
    	super("! TUTORIAL !");
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	this.k=1;
    	addMouseListener(this);
		addMouseMotionListener(this);

		jPanel1 = new javax.swing.JPanel();
        newGame = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
    

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent ev) {
            	k=1;
            	changeBackground();
            	home.setVisible(false);
            	newGame.setVisible(false);
                ViewControllerForModel.getInstance().closeTutorial();
                ViewControllerForModel.getInstance().openStartWindow();
               
               	
                 }            
          });
        setResizable(false);
        setPreferredSize(new java.awt.Dimension(850, 650));
        setResizable(false);

        jPanel1.setLayout(null);
        
        newGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/np.png"))); // NOI18N
        newGame.setContentAreaFilled(false);
        newGame.setPreferredSize(new java.awt.Dimension(220, 70));
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        
        newGame.setVisible(false);
        home.setVisible(false);
        
        jPanel1.add(newGame);
        newGame.setBounds(610, 540, 220, 70);
        
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/hm.png"))); // NOI18N
        
        home.setContentAreaFilled(false);
        home.setPreferredSize(new java.awt.Dimension(220, 70));
        jPanel1.add(home);
        home.setBounds(20, 540, 220, 70);
        

        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        
        changeBackground();
        pack();
    }// </editor-fold>  

    public void changeBackground(){
    	
        switch (k) {
		case 1:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			break;
		case 2:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);	
			break;
		case 3:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
	
			break;
		case 4:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			
			break;
		case 5:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			
			break;
		case 6:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
	
			break;
			
		case 7:
			
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			break;
		case 8:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			
			break;
		case 9:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
	
			break;
		case 10:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
			 break;
		case 11:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);

			break;
			
		case 12:
			 this.image = new javax.swing.ImageIcon(getClass().getResource("/jarcassonne/img/tutorial/"+k+".jpg"));
						        jLabel1.setIcon(image);
						

			break;

		}
    }
    
    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	ViewControllerForModel.getInstance().closeTutorial();
    	ViewControllerForModel.getInstance().openNewGameWindow();
    	k=1;
    	changeBackground();
		newGame.setVisible(false);
		home.setVisible(false);
    } 
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {
    	ViewControllerForModel.getInstance().closeTutorial();
    	ViewControllerForModel.getInstance().openStartWindow();
    	k=1;
    	changeBackground();
		newGame.setVisible(false);
		home.setVisible(false);
    	
    } 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialWindow().setVisible(true);
            }
        });
    }
                 
	@Override
	public void mousePressed(MouseEvent arg0) {
		System.out.println(arg0.getX()+", "+arg0.getY());
		 switch (k) {
			case 1:
				if(arg0.getX()>470 && arg0.getY()>300 && arg0.getX()<560 && arg0.getY()<400 && arg0.getButton()==1){
					k++;
					changeBackground();
				}
				break;
			case 2:
				if(arg0.getX()>470 && arg0.getY()>300 && arg0.getX()<560 && arg0.getY()<400 && arg0.getButton()==1){
					k++;
					changeBackground();
				}
				
				break;
			case 3:
				if(arg0.getX()>470 && arg0.getY()>300 && arg0.getX()<560 && arg0.getY()<400 && arg0.getButton()==1){
					k++;
					changeBackground();
				}
		
				break;
			case 4:
				System.out.println(""+ arg0.getX()+ "   "+ arg0.getY());
				if(arg0.getButton()==2){
					k++;
					changeBackground();
					}
				if(arg0.getButton()==1 && arg0.getX()>360 && arg0.getY()>560 && arg0.getX()<440 && arg0.getY()<610){
					k++;
					changeBackground();
					}
				
				break;
			case 5:
				if(arg0.getX()>260 && arg0.getY()>300 && arg0.getX()<370 && arg0.getY()<400 && arg0.getButton()==1){
					k++;
					changeBackground();
					}
				
				break;
			case 6:
				if(arg0.getButton()==3){
					k++;
					changeBackground();
					this.defaultCursor=getCursor();
					try {
						 img = ImageIO.read(NewGameWindow.class.getResourceAsStream("/jarcassonne/img/Seguaci/FollowerCursor.png"));
						} catch (IOException e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						Toolkit t = Toolkit.getDefaultToolkit();
						this.cursore = t.createCustomCursor(img,new Point(0,0),"cur");
						
						setCursor(cursore);
					}
				
		
				break;
				
			case 7:
				if(arg0.getButton()==1){
					if(arg0.getX()>340 && arg0.getY()>340 && arg0.getX()<375 && arg0.getY()<375){
					k++;
					changeBackground();
					setCursor(defaultCursor);
					}
				}
				break;
			case 8:
				if(arg0.getX()>470 && arg0.getY()>300 && arg0.getX()<560 && arg0.getY()<400 && arg0.getButton()==1){
					k++;
					changeBackground();
				}
				break;
			case 9:
				 if(arg0.getButton()==3){
						k++;
						changeBackground();
						setCursor(cursore);
						}
		
				break;
			case 10:
				 if(arg0.getButton()==3){
						k++;
						changeBackground();
						setCursor(defaultCursor);
						
						}
				 break;
				 
			case 11:
				if(arg0.getButton()==1 && arg0.getX()>645 && arg0.getX()<770 && arg0.getY()>560 && arg0.getY()<630){
					k++;
					changeBackground();
					newGame.setVisible(true);
					home.setVisible(true);
				}

				break;
			}
		 
	
		
	}

	@Override
	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseClicked(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseDragged(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseMoved(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	

    // Variables declaration - do not modify                     
	private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGame;
    
    private ImageIcon image;
    protected BufferedImage img;
	protected Cursor cursore;
	protected Cursor defaultCursor;

    // End of variables declaration  
}